apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-1.12
  namespace: fleet1
spec:
  replicas: 2
  selector:
    project: lab7
    service: web
    version: "0.1"
  template:
    metadata:
      name: nginx
      labels:
        project: lab7
        service: web
        version: "0.1"
    spec:
      containers:
      - name: nginx
        image: nginx:1.12.0
        ports:
        - containerPort: 80
