apiVersion: v1
kind: Pod
metadata:
  name: our-nginx
  namespace: fleet1
  labels:
    project: lab3
    service: web
    version: "0.1"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
