apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: fleet1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.12.0
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: fleet1
  labels:
    run: nginx
spec:
  selector:
    run: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
