kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: fleet1
spec:
  type: LoadBalancer
  selector:
    project: lab7
    service: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
